---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml

  roles:
    - geerlingguy.homebrew
    - geerlingguy.dotfiles
    - name: geerlingguy.mas
      when: mas_installed_apps
    - { role: dosullivan.kops, kops_version: 1.5.1 }
    - role: telusdigital.kubectl 

  tasks:
    - include: tasks/ansible-setup.yml

    - include: tasks/sudoers.yml
      when: configure_sudoers

    - include: tasks/terminal.yml
      when: configure_terminal

    - include: tasks/osx.yml
      when: configure_osx
